### ISSUE TITLE
automatic tags?

### ISSUE THREAD

**Issue by louis030195** [different-ai/file-organizer-2000#3]
im always figuring out tags i should add

also struggle with "s" annoying, like I have #physic and #physics, just a pain lol 

maybe something cool:
- check all unique tags in my vault and add tags at some point in my workflow to notes (using basic gpt)

not sure how the new metadata thing of obsidian works (properties)

i dont really like their new properties thing - it seems to be for nontech people

i tend to add tags at the end of my notes now because i dont like the visual noise

**Comment by ashgansh** [comment]
hi @louis030195 I added automatic tags, but it needs to enabled :)

since, there's not many users i'm going to commit a change to make them go to the bottom instead of the top (as i designed it initially :))


<img width="976" alt="Screenshot 2024-01-19 at 16 35 07" src="https://github.com/different-ai/file-organizer-2000/assets/11430621/3ba580a8-04f8-4a6f-9396-a87d2ba15536">
