### ISSUE TITLE
feature request: scheduler for file organizing

### ISSUE THREAD

**Issue by oscaromsn** [different-ai/file-organizer-2000#4]
Hi, greetings from Brazil!

Really amazing work, man - congrats!

I was wondering if in the future there might be a feature that allows setting the time for file organizing. That's because in my workflow (and I think maybe others feel this too), I need to do some mass organization for a while before everything becomes ready to go to the right place.

Thank you again,
Bye!

**Comment by ashgansh** [comment]
hi @oscaromsn thanks for the feedback.

that makes sense and i really want to be able to solve this problem especially for people who are in a very disorganized state  (i'm one of them 😁).

so if I understand step one in this setup would be to go to settings and for example do "Organizer Schedule: to 6pm every day"

And what do you think should happen next? some sort of "dry run"?

(I've been holding out on "mass" organization right now, because I really want to nail the UX correctly if the program starts to move all your files)

**Comment by ashgansh** [comment]
Or maybe a different variation would be: "every new files created since yesterday should be sorted at a certain time?", but not the ones before that

**Comment by oscaromsn** [comment]
I was considering a simple setup to provide the time in hh:mm format, but I became really interested in the possibility of being able to supply the time window using natural language
